### ISSUE TITLE
야무 강사님 Vue에 대해서 여쭤보고 싶은게 있습니다.

### ISSUE THREAD

**Issue by dlqjaen** [yamoo9/vue-simple#1]
야무님 FastCampus 4기 이범두입니다.
vue의 가상돔 질문드립니다.
vue나 react의 가장 큰 장점은 가상돔인 것 같은데,
가상돔을 사용하는 vue를 사용하여 애플리케이션을 만드나, jquery를 사용하여 만드나
결국 브라우저에 랜더링된 node를 업데이트 하는 순간은 동일한 것 같습니다.

(vue를 쓰나 jquery쓰나 reflow/repaint는 동일하게 발생한다고 생각합니다.)
결국 브라우저에 랜더링된 node가 업데이트 되기 전, DOM을 탐색하느냐(dom,css tree를 생성하느냐) 안하느냐(가상돔) 차이인 것 같은데 
실제로 체감할 수 있는 부분이나 케이스가 있는지 궁금합니다.

**Comment by yamoo9** [comment]
범두님. 아래 문구가 질문에 대한 적절한 답변을 대변해주지 않나 생각해보네요.

> The truth is, there may be no way to actually figure out if using Virtual DOM is faster than an approach that updates the DOM directly, because it depends on a million different factors, but mostly it depends on how well you optimize your application.

이를 풀어보면_

> 진실은 아마도 Virtual DOM을 사용하는 것이 DOM을 직접 접근하고 조작하는 것 보다 빠르다는 것을 증명할 방법이 없을지도 모릅니다. 이유는 수백만 가지 요소에 의해 결과가 달라질 수 있기 때문입니다. 하지만 정작 중요한 것은 애플리케이션에 얼마나 최적화되어 있느냐 일 겁니다.

**Front-End 개발에서 하는 주요한 업무가 UI 제작 이기에 보다 빠르고 쉽게 구현할 수 있는 방법이 제공된다면?** 그 방법을 적극 사용해야할 필요가 있지 않을까 싶습니다. 기존의 DOM 접근/조작 방식은 낙후되어 있고, 손이 많이 갑니다. 이 점은 여러 전문가들이 지적한 DOM의 고질적인 문제이기도 하죠.

**Virtural DOM이 우리에게 제공해주는 것은 기존보다 간결한 제작 방식입니다.** 즉, **단순성(Simplicity)은 제작자로 하여금 정신적 스트레스를 덜 받게 하고, UI를 보다 쉽게 구현할 방법을 제시했다는 점입니다.** 속도도 속도지만, 정작 중요한 대목은 이 부분이 아닐까 합니다. :-)

범두님은 수업을 통해 DOM 스크립팅, jQuery 스크립팅, Virtual DOM 스타일의 개발 방법을 모두 경험하셨습니다. 속도면에서는 아무래도 DOM 스크립팅이 빠르겠지만, 재사용을 위해 만들어야 할 유틸리티가 많을 거 같고, jQuery는 많은 유틸리티를 제공해주지만 속도는 느리고, 일관된 코드 스타일이 없어 엉킨 스파게티 코드가 만들어질 가능성이 다분하죠. (팀 작업 시)

반면 **프레임워크는 속도도 DOM 스크립팅 못지 않게 빠르고, jQuery와 달리 개발을 위한 코드 틀(Frame)을 제공해주니 코드가 스파게티가 될 염려도 없겠죠. ^^ 다만 학습 비용이 높을 뿐.**

무엇을 선택하던 우리가 선택할 포인트는 주어진 조건내에서 **사용자를 생각하고, 사용자를 위하는 멋진 웹 애플리케이션 인터페이스 구현**에 있다고 봅니다. ^^

##### 참고

- [Virtual DOM의 실질적 이익에 관한 이야기](https://www.accelebrate.com/blog/the-real-benefits-of-the-virtual-dom-in-react-js/)
- [Virtual DOM vs DOM 간 차이점](http://reactkungfu.com/2015/10/the-difference-between-virtual-dom-and-dom/)

**Comment by dlqjaen** [comment]
감사합니다 야무님! 의문에 답이 된거 같습니다
